on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push (Production)

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install packages
        run: npm install --legacy-peer-deps

      - name: Set environment
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV_PRODUCTION }}" >> .env.staging
          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV_PRODUCTION }}" >> .env.staging
          echo "VITE_SALT_KEY=${{ secrets.VITE_SALT_KEY }}" >> .env.staging
          echo "VITE_PUSHER_KEY=${{ secrets.VITE_PUSHER_KEY }}" >> .env.staging
          echo "VITE_PUSHER_SECRET=${{ secrets.VITE_PUSHER_SECRET }}" >> .env.staging
          echo "VITE_PUSHER_APP_ID=${{ secrets.VITE_PUSHER_APP_ID }}" >> .env.staging
          echo "VITE_PUSHER_PORT=${{ secrets.VITE_PUSHER_PORT }}" >> .env.staging
          echo "VITE_PUSHER_SCHEME=${{ secrets.VITE_PUSHER_SCHEME }}" >> .env.staging
          echo "VITE_PUSHER_APP_CLUSTER=${{ secrets.VITE_PUSHER_APP_CLUSTER }}" >> .env.staging
          echo "VITE_API_URL=${{ secrets.VITE_API_URL_PRODUCTION }}" >> .env.staging
          echo "VITE_OFFICE_URL=${{ secrets.VITE_OFFICE_URL_PRODUCTION }}" >> .env.staging

      - name: Build for staging
        run: npm run build-staging

      # sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST_PRODUCTION }}
          username: ${{ secrets.FTP_USERNAME_PRODUCTION }}
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
          local-dir: ./dist/
          server-dir: /
